modLoader="javafml"
loaderVersion="${neo_version}"
license="${mod_license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mekanism-elements"
logoFile="logo.png"
credits="${mod_authors}"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${loader_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mekanism"
    type="required"
    versionRange="${mekanism_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mekanismgenerators"
    type="required"
    versionRange="${mekanism_generators_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="${jei_version}"
    ordering="NONE"
    side="BOTH"